name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking-changes-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/breaking-changes-label@b51360a7cc39cb3deb5ae1bf0bfb121fe7ee0a4e
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
